name = "db-sync-service"
main = "cloudflare/db-worker.js"
compatibility_date = "2026-03-11"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "dbsync.xiaomiao.win", custom_domain = true }
]

[triggers]
crons = ["* * * * *"]

[vars]
STRIPE_PRODUCT_NAME = "数据库同步"
SOCKS5_PROXY_URL = "socks5://165.154.200.47:1080"

[[kv_namespaces]]
binding = "DB_STATE"
id = "d5cdde5310614ee6a31e794785470caa"
